### PR TITLE
Update README with new information for deployments to prod and dev (CU-86du8ncph)

### PR DESCRIPTION
**Pull request by Darrickg**

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-86du8ncph Add some info to the Sensor README.md about turning off/and dev and staging servers](https://app.clickup.com/t/86du8ncph)

**Comment by Darrickg** [comment]
can you guys ensure that the information i wrote is correct and accurate

**Comment by Darrickg** [comment]
@CCheng00 im specifically requesting you to review this

**Review by CCheng00 — APPROVED** [review]
Looks good!

**Pull request merged**
