### PR TITLE
Write 1 byte when initializing Door ID (CU-8678xpmpu)

### PR DESCRIPTION
**Pull request by johnny-brave**
During initialization of the Door Sensor, the value written into EEPROM was not specified as a 1 byte data field. This caused the address fields for the long stillness timer to be overwritten with 0's. This bugfix writes uin8_t data to the door sensor upon initialization to prevent  unintended overwriting of other flash addresses.

Test plan:
---

- [x] Flash firmware onto a new boron and confirm that all initial values are correct including the long stillness timer
- [x] Write new value in the long-stillness timer using the particle console function and echo to confirm that it was saved
- [x] Reset boron and confirm that the new value persists through reset
- [x] Flash firmware onto an existing boron and confirm that previous memory values are written correctly

### CODE REVIEW

**Review by micahdbak — COMMENTED** [review]
Hi Johnny, please merge in the latest changes from main. This will resolve the Travis checks that are currently failing

**Review by micahdbak — APPROVED** [review]
Looks good to merge!

**Review by trisapeace — COMMENTED** [review]
Good catch @johnny-brave ! Nice fix. Glad you figured it out.

Did you also check to make sure that writing a new door sensor doesn't overwrite the long stillness timer?

**Comment by trisapeace** [comment]
P.S. Also, for a PR like this where there are a lot of commits with changes and messages like "formatting", it would lead to a cleaner commit history to use "Squash and Merge" instead of "Merge". This will create a single commit in the `main` branch and you can write a single commit message explaining one time what it was that this PR does.

**Pull request merged**
