### PR TITLE
Allow Duration Alerts to Repeat (CU-8678tmmew)

### PR DESCRIPTION
**Pull request by johnny-brave**
This pull request removes the condition of `!hasDurationAlertBeenSent` when triggering a duration alert. `state2_duration_timer` is also zeroed to the current clock time upon triggering a duration alert.
---
Test Plan:

- [x] set duration timer to 20 seconds and stillness timer to 1 min
- [x] close the door sensor and enter occupancy by shaking the test sensor
- [x] remain still for 1 minute 
- [x] verify that 1 stillness alert and 3 duration alerts have been triggered
- [x] open and close the door sensor, enter occupancy again
- [x] repeat step 3 again, but with movement (staying in state 2)
- [x] verify that 3 duration alerts have been triggered and no stillness alert

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-8678tmmew Allow Duration Alerts to Repeat](https://app.clickup.com/t/8678tmmew)

**Review by micahdbak — COMMENTED** [review]
Changes look good; simple and should work!

From what I know about the server, subsequent Duration alerts should be received and handled in the same way as additional Stillness alerts.

I'll wait for you to complete the Test Plan and report back on what happens before I approve this PR.

**Comment by trisapeace** [comment]
When you merge this, can you please use the "Squash and Merge" option? Thank you! That will help keep our commit history readable :smile:

**Review by micahdbak — APPROVED** [review]
Approved, looks good! Feel free to squash and merge whenever.

**Pull request merged**
