### PR TITLE
update dashboard (CU-86du7hv9b)

### PR DESCRIPTION
**Pull request by elanawood**
Updated the new client dashboard to reflect the new incident categories. Added a migration script to set the default value for incident categories.

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-86du7hv9b Update Default Incident Categories on Sensors Dashboard](https://app.clickup.com/t/86du7hv9b)

**Review by micahdbak — COMMENTED** [review]
Looks good too! Please merge your other PR first, then this one. You'll need to update your migration script to become 51, not 50, when you do this, so I'll approve when you've made those changes.

**Comment by micahdbak** [comment]
@elanawood , you'll need to update this PR, I just merged your other one. Please merge in changes from main + make your SQL migration file be for 51 instead!

**Review by micahdbak — APPROVED** [review]
Looks good 👍

**Pull request merged**
