### PR TITLE
drop unused tables (CU-86du4nq8w)

### PR DESCRIPTION
**Pull request by elanawood**
Dropping unused tables!

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-86du4nq8w Drop unused tables for Sensors](https://app.clickup.com/t/86du4nq8w)

**Review by micahdbak — APPROVED** [review]
wonderful tysm 👍

**Comment by micahdbak** [comment]
wait no

**Comment by micahdbak** [comment]
update the CHANGELOG.md before merging!!!

**Comment by micahdbak** [comment]
oops - new pr

**Pull request closed without merging**
